
model_path:
  huggingface: "/home/lukelo/.cache/huggingface"  # directory to store downloaded models

# Dataset
data:
  root: "/home/lukelo/OpenEMMA/v1.0-mini"  # Path to nuScenes dataset
  version: "v1.0-mini"  # Dataset version (v1.0-mini, v1.0-trainval, v1.0-test)
  results: "results"  # Directory to store results

# Prediction Parameters (do not change)
prediction:
  obs_len: 6  # Number of past observations (frames)
  fut_len: 6  # Number of future predictions (frames)
  ext_len: 2  # Extra length for calculations (frames)
